services:
  traefik:
    image: traefik:v2.11
    user: '0:0'
    environment:
      - DOCKER_API_VERSION=1.44
    command:
      - '--providers.docker=true'
      - '--providers.docker.swarmMode=true' # Attiva il supporto Swarm
      - '--providers.docker.exposedByDefault=false'
      - '--providers.docker.endpoint=unix:///var/run/docker.sock'

      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'

      - '--certificatesresolvers.myresolver.acme.httpchallenge=true'
      - '--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web'
      - '--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname == ubuntu
    networks:
      - webnet

  me:
    image: dcdavidev/me:latest
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - EMAIL_USER=${EMAIL_USER}
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.me.rule=Host(`${HOST}`) || Host(`www.${HOST}`)'
        - 'traefik.http.routers.me.entrypoints=websecure'
        - 'traefik.http.routers.me.tls.certresolver=myresolver'
        - 'traefik.http.services.me.loadbalancer.server.port=3000'
        - 'traefik.docker.network=me_webnet'
      restart_policy:
        condition: on-failure
    networks:
      - webnet

networks:
  webnet:
    driver: overlay
    attachable: true

volumes:
  traefik-certificates:
