/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `OneTimePassword` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums.js';
import type * as Prisma from '../internal/prismaNamespace.js';

/**
 * Model OneTimePassword
 *
 */
export type OneTimePasswordModel =
  runtime.Types.Result.DefaultSelection<Prisma.$OneTimePasswordPayload>;

export type AggregateOneTimePassword = {
  _count: OneTimePasswordCountAggregateOutputType | null;
  _min: OneTimePasswordMinAggregateOutputType | null;
  _max: OneTimePasswordMaxAggregateOutputType | null;
};

export type OneTimePasswordMinAggregateOutputType = {
  id: string | null;
  email: string | null;
  code: string | null;
  expiresAt: Date | null;
  createdAt: Date | null;
};

export type OneTimePasswordMaxAggregateOutputType = {
  id: string | null;
  email: string | null;
  code: string | null;
  expiresAt: Date | null;
  createdAt: Date | null;
};

export type OneTimePasswordCountAggregateOutputType = {
  id: number;
  email: number;
  code: number;
  expiresAt: number;
  createdAt: number;
  _all: number;
};

export type OneTimePasswordMinAggregateInputType = {
  id?: true;
  email?: true;
  code?: true;
  expiresAt?: true;
  createdAt?: true;
};

export type OneTimePasswordMaxAggregateInputType = {
  id?: true;
  email?: true;
  code?: true;
  expiresAt?: true;
  createdAt?: true;
};

export type OneTimePasswordCountAggregateInputType = {
  id?: true;
  email?: true;
  code?: true;
  expiresAt?: true;
  createdAt?: true;
  _all?: true;
};

export type OneTimePasswordAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which OneTimePassword to aggregate.
   */
  where?: Prisma.OneTimePasswordWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OneTimePasswords to fetch.
   */
  orderBy?:
    | Prisma.OneTimePasswordOrderByWithRelationInput
    | Prisma.OneTimePasswordOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.OneTimePasswordWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OneTimePasswords from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OneTimePasswords.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned OneTimePasswords
   **/
  _count?: true | OneTimePasswordCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: OneTimePasswordMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: OneTimePasswordMaxAggregateInputType;
};

export type GetOneTimePasswordAggregateType<
  T extends OneTimePasswordAggregateArgs,
> = {
  [P in keyof T & keyof AggregateOneTimePassword]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOneTimePassword[P]>
    : Prisma.GetScalarType<T[P], AggregateOneTimePassword[P]>;
};

export type OneTimePasswordGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.OneTimePasswordWhereInput;
  orderBy?:
    | Prisma.OneTimePasswordOrderByWithAggregationInput
    | Prisma.OneTimePasswordOrderByWithAggregationInput[];
  by:
    | Prisma.OneTimePasswordScalarFieldEnum[]
    | Prisma.OneTimePasswordScalarFieldEnum;
  having?: Prisma.OneTimePasswordScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: OneTimePasswordCountAggregateInputType | true;
  _min?: OneTimePasswordMinAggregateInputType;
  _max?: OneTimePasswordMaxAggregateInputType;
};

export type OneTimePasswordGroupByOutputType = {
  id: string;
  email: string;
  code: string;
  expiresAt: Date;
  createdAt: Date;
  _count: OneTimePasswordCountAggregateOutputType | null;
  _min: OneTimePasswordMinAggregateOutputType | null;
  _max: OneTimePasswordMaxAggregateOutputType | null;
};

type GetOneTimePasswordGroupByPayload<T extends OneTimePasswordGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<OneTimePasswordGroupByOutputType, T['by']> & {
        [P in keyof T &
          keyof OneTimePasswordGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OneTimePasswordGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OneTimePasswordGroupByOutputType[P]>;
      }
    >
  >;

export type OneTimePasswordWhereInput = {
  AND?: Prisma.OneTimePasswordWhereInput | Prisma.OneTimePasswordWhereInput[];
  OR?: Prisma.OneTimePasswordWhereInput[];
  NOT?: Prisma.OneTimePasswordWhereInput | Prisma.OneTimePasswordWhereInput[];
  id?: Prisma.StringFilter<'OneTimePassword'> | string;
  email?: Prisma.StringFilter<'OneTimePassword'> | string;
  code?: Prisma.StringFilter<'OneTimePassword'> | string;
  expiresAt?: Prisma.DateTimeFilter<'OneTimePassword'> | Date | string;
  createdAt?: Prisma.DateTimeFilter<'OneTimePassword'> | Date | string;
};

export type OneTimePasswordOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  email?: Prisma.SortOrder;
  code?: Prisma.SortOrder;
  expiresAt?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type OneTimePasswordWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    AND?: Prisma.OneTimePasswordWhereInput | Prisma.OneTimePasswordWhereInput[];
    OR?: Prisma.OneTimePasswordWhereInput[];
    NOT?: Prisma.OneTimePasswordWhereInput | Prisma.OneTimePasswordWhereInput[];
    email?: Prisma.StringFilter<'OneTimePassword'> | string;
    code?: Prisma.StringFilter<'OneTimePassword'> | string;
    expiresAt?: Prisma.DateTimeFilter<'OneTimePassword'> | Date | string;
    createdAt?: Prisma.DateTimeFilter<'OneTimePassword'> | Date | string;
  },
  'id'
>;

export type OneTimePasswordOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  email?: Prisma.SortOrder;
  code?: Prisma.SortOrder;
  expiresAt?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  _count?: Prisma.OneTimePasswordCountOrderByAggregateInput;
  _max?: Prisma.OneTimePasswordMaxOrderByAggregateInput;
  _min?: Prisma.OneTimePasswordMinOrderByAggregateInput;
};

export type OneTimePasswordScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.OneTimePasswordScalarWhereWithAggregatesInput
    | Prisma.OneTimePasswordScalarWhereWithAggregatesInput[];
  OR?: Prisma.OneTimePasswordScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.OneTimePasswordScalarWhereWithAggregatesInput
    | Prisma.OneTimePasswordScalarWhereWithAggregatesInput[];
  id?: Prisma.StringWithAggregatesFilter<'OneTimePassword'> | string;
  email?: Prisma.StringWithAggregatesFilter<'OneTimePassword'> | string;
  code?: Prisma.StringWithAggregatesFilter<'OneTimePassword'> | string;
  expiresAt?:
    | Prisma.DateTimeWithAggregatesFilter<'OneTimePassword'>
    | Date
    | string;
  createdAt?:
    | Prisma.DateTimeWithAggregatesFilter<'OneTimePassword'>
    | Date
    | string;
};

export type OneTimePasswordCreateInput = {
  id?: string;
  email: string;
  code: string;
  expiresAt: Date | string;
  createdAt?: Date | string;
};

export type OneTimePasswordUncheckedCreateInput = {
  id?: string;
  email: string;
  code: string;
  expiresAt: Date | string;
  createdAt?: Date | string;
};

export type OneTimePasswordUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  email?: Prisma.StringFieldUpdateOperationsInput | string;
  code?: Prisma.StringFieldUpdateOperationsInput | string;
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type OneTimePasswordUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  email?: Prisma.StringFieldUpdateOperationsInput | string;
  code?: Prisma.StringFieldUpdateOperationsInput | string;
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type OneTimePasswordCreateManyInput = {
  id?: string;
  email: string;
  code: string;
  expiresAt: Date | string;
  createdAt?: Date | string;
};

export type OneTimePasswordUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  email?: Prisma.StringFieldUpdateOperationsInput | string;
  code?: Prisma.StringFieldUpdateOperationsInput | string;
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type OneTimePasswordUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  email?: Prisma.StringFieldUpdateOperationsInput | string;
  code?: Prisma.StringFieldUpdateOperationsInput | string;
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type OneTimePasswordCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  email?: Prisma.SortOrder;
  code?: Prisma.SortOrder;
  expiresAt?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type OneTimePasswordMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  email?: Prisma.SortOrder;
  code?: Prisma.SortOrder;
  expiresAt?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type OneTimePasswordMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  email?: Prisma.SortOrder;
  code?: Prisma.SortOrder;
  expiresAt?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type StringFieldUpdateOperationsInput = {
  set?: string;
};

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string;
};

export type OneTimePasswordSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    email?: boolean;
    code?: boolean;
    expiresAt?: boolean;
    createdAt?: boolean;
  },
  ExtArgs['result']['oneTimePassword']
>;

export type OneTimePasswordSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    email?: boolean;
    code?: boolean;
    expiresAt?: boolean;
    createdAt?: boolean;
  },
  ExtArgs['result']['oneTimePassword']
>;

export type OneTimePasswordSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    email?: boolean;
    code?: boolean;
    expiresAt?: boolean;
    createdAt?: boolean;
  },
  ExtArgs['result']['oneTimePassword']
>;

export type OneTimePasswordSelectScalar = {
  id?: boolean;
  email?: boolean;
  code?: boolean;
  expiresAt?: boolean;
  createdAt?: boolean;
};

export type OneTimePasswordOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'id' | 'email' | 'code' | 'expiresAt' | 'createdAt',
  ExtArgs['result']['oneTimePassword']
>;

export type $OneTimePasswordPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'OneTimePassword';
  objects: {};
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      email: string;
      code: string;
      expiresAt: Date;
      createdAt: Date;
    },
    ExtArgs['result']['oneTimePassword']
  >;
  composites: {};
};

export type OneTimePasswordGetPayload<
  S extends boolean | null | undefined | OneTimePasswordDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$OneTimePasswordPayload, S>;

export type OneTimePasswordCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = Omit<
  OneTimePasswordFindManyArgs,
  'select' | 'include' | 'distinct' | 'omit'
> & {
  select?: OneTimePasswordCountAggregateInputType | true;
};

export interface OneTimePasswordDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['OneTimePassword'];
    meta: { name: 'OneTimePassword' };
  };
  /**
   * Find zero or one OneTimePassword that matches the filter.
   * @param {OneTimePasswordFindUniqueArgs} args - Arguments to find a OneTimePassword
   * @example
   * // Get one OneTimePassword
   * const oneTimePassword = await prisma.oneTimePassword.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OneTimePasswordFindUniqueArgs>(
    args: Prisma.SelectSubset<T, OneTimePasswordFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__OneTimePasswordClient<
    runtime.Types.Result.GetResult<
      Prisma.$OneTimePasswordPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one OneTimePassword that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OneTimePasswordFindUniqueOrThrowArgs} args - Arguments to find a OneTimePassword
   * @example
   * // Get one OneTimePassword
   * const oneTimePassword = await prisma.oneTimePassword.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OneTimePasswordFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, OneTimePasswordFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__OneTimePasswordClient<
    runtime.Types.Result.GetResult<
      Prisma.$OneTimePasswordPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first OneTimePassword that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OneTimePasswordFindFirstArgs} args - Arguments to find a OneTimePassword
   * @example
   * // Get one OneTimePassword
   * const oneTimePassword = await prisma.oneTimePassword.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OneTimePasswordFindFirstArgs>(
    args?: Prisma.SelectSubset<T, OneTimePasswordFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__OneTimePasswordClient<
    runtime.Types.Result.GetResult<
      Prisma.$OneTimePasswordPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first OneTimePassword that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OneTimePasswordFindFirstOrThrowArgs} args - Arguments to find a OneTimePassword
   * @example
   * // Get one OneTimePassword
   * const oneTimePassword = await prisma.oneTimePassword.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OneTimePasswordFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, OneTimePasswordFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__OneTimePasswordClient<
    runtime.Types.Result.GetResult<
      Prisma.$OneTimePasswordPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more OneTimePasswords that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OneTimePasswordFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OneTimePasswords
   * const oneTimePasswords = await prisma.oneTimePassword.findMany()
   *
   * // Get first 10 OneTimePasswords
   * const oneTimePasswords = await prisma.oneTimePassword.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const oneTimePasswordWithIdOnly = await prisma.oneTimePassword.findMany({ select: { id: true } })
   *
   */
  findMany<T extends OneTimePasswordFindManyArgs>(
    args?: Prisma.SelectSubset<T, OneTimePasswordFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$OneTimePasswordPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >;

  /**
   * Create a OneTimePassword.
   * @param {OneTimePasswordCreateArgs} args - Arguments to create a OneTimePassword.
   * @example
   * // Create one OneTimePassword
   * const OneTimePassword = await prisma.oneTimePassword.create({
   *   data: {
   *     // ... data to create a OneTimePassword
   *   }
   * })
   *
   */
  create<T extends OneTimePasswordCreateArgs>(
    args: Prisma.SelectSubset<T, OneTimePasswordCreateArgs<ExtArgs>>
  ): Prisma.Prisma__OneTimePasswordClient<
    runtime.Types.Result.GetResult<
      Prisma.$OneTimePasswordPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many OneTimePasswords.
   * @param {OneTimePasswordCreateManyArgs} args - Arguments to create many OneTimePasswords.
   * @example
   * // Create many OneTimePasswords
   * const oneTimePassword = await prisma.oneTimePassword.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends OneTimePasswordCreateManyArgs>(
    args?: Prisma.SelectSubset<T, OneTimePasswordCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many OneTimePasswords and returns the data saved in the database.
   * @param {OneTimePasswordCreateManyAndReturnArgs} args - Arguments to create many OneTimePasswords.
   * @example
   * // Create many OneTimePasswords
   * const oneTimePassword = await prisma.oneTimePassword.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many OneTimePasswords and only return the `id`
   * const oneTimePasswordWithIdOnly = await prisma.oneTimePassword.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends OneTimePasswordCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<
      T,
      OneTimePasswordCreateManyAndReturnArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$OneTimePasswordPayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a OneTimePassword.
   * @param {OneTimePasswordDeleteArgs} args - Arguments to delete one OneTimePassword.
   * @example
   * // Delete one OneTimePassword
   * const OneTimePassword = await prisma.oneTimePassword.delete({
   *   where: {
   *     // ... filter to delete one OneTimePassword
   *   }
   * })
   *
   */
  delete<T extends OneTimePasswordDeleteArgs>(
    args: Prisma.SelectSubset<T, OneTimePasswordDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__OneTimePasswordClient<
    runtime.Types.Result.GetResult<
      Prisma.$OneTimePasswordPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one OneTimePassword.
   * @param {OneTimePasswordUpdateArgs} args - Arguments to update one OneTimePassword.
   * @example
   * // Update one OneTimePassword
   * const oneTimePassword = await prisma.oneTimePassword.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends OneTimePasswordUpdateArgs>(
    args: Prisma.SelectSubset<T, OneTimePasswordUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__OneTimePasswordClient<
    runtime.Types.Result.GetResult<
      Prisma.$OneTimePasswordPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more OneTimePasswords.
   * @param {OneTimePasswordDeleteManyArgs} args - Arguments to filter OneTimePasswords to delete.
   * @example
   * // Delete a few OneTimePasswords
   * const { count } = await prisma.oneTimePassword.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends OneTimePasswordDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, OneTimePasswordDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more OneTimePasswords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OneTimePasswordUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OneTimePasswords
   * const oneTimePassword = await prisma.oneTimePassword.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends OneTimePasswordUpdateManyArgs>(
    args: Prisma.SelectSubset<T, OneTimePasswordUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more OneTimePasswords and returns the data updated in the database.
   * @param {OneTimePasswordUpdateManyAndReturnArgs} args - Arguments to update many OneTimePasswords.
   * @example
   * // Update many OneTimePasswords
   * const oneTimePassword = await prisma.oneTimePassword.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more OneTimePasswords and only return the `id`
   * const oneTimePasswordWithIdOnly = await prisma.oneTimePassword.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends OneTimePasswordUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<
      T,
      OneTimePasswordUpdateManyAndReturnArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$OneTimePasswordPayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one OneTimePassword.
   * @param {OneTimePasswordUpsertArgs} args - Arguments to update or create a OneTimePassword.
   * @example
   * // Update or create a OneTimePassword
   * const oneTimePassword = await prisma.oneTimePassword.upsert({
   *   create: {
   *     // ... data to create a OneTimePassword
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OneTimePassword we want to update
   *   }
   * })
   */
  upsert<T extends OneTimePasswordUpsertArgs>(
    args: Prisma.SelectSubset<T, OneTimePasswordUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__OneTimePasswordClient<
    runtime.Types.Result.GetResult<
      Prisma.$OneTimePasswordPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of OneTimePasswords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OneTimePasswordCountArgs} args - Arguments to filter OneTimePasswords to count.
   * @example
   * // Count the number of OneTimePasswords
   * const count = await prisma.oneTimePassword.count({
   *   where: {
   *     // ... the filter for the OneTimePasswords we want to count
   *   }
   * })
   **/
  count<T extends OneTimePasswordCountArgs>(
    args?: Prisma.Subset<T, OneTimePasswordCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<
            T['select'],
            OneTimePasswordCountAggregateOutputType
          >
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a OneTimePassword.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OneTimePasswordAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends OneTimePasswordAggregateArgs>(
    args: Prisma.Subset<T, OneTimePasswordAggregateArgs>
  ): Prisma.PrismaPromise<GetOneTimePasswordAggregateType<T>>;

  /**
   * Group by OneTimePassword.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OneTimePasswordGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends OneTimePasswordGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OneTimePasswordGroupByArgs['orderBy'] }
      : { orderBy?: OneTimePasswordGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    'Field ',
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ];
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, OneTimePasswordGroupByArgs, OrderByArg> &
      InputErrors
  ): {} extends InputErrors
    ? GetOneTimePasswordGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the OneTimePassword model
   */
  readonly fields: OneTimePasswordFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OneTimePassword.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OneTimePasswordClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise';
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null
  ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the OneTimePassword model
 */
export interface OneTimePasswordFieldRefs {
  readonly id: Prisma.FieldRef<'OneTimePassword', 'String'>;
  readonly email: Prisma.FieldRef<'OneTimePassword', 'String'>;
  readonly code: Prisma.FieldRef<'OneTimePassword', 'String'>;
  readonly expiresAt: Prisma.FieldRef<'OneTimePassword', 'DateTime'>;
  readonly createdAt: Prisma.FieldRef<'OneTimePassword', 'DateTime'>;
}

// Custom InputTypes
/**
 * OneTimePassword findUnique
 */
export type OneTimePasswordFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OneTimePassword
   */
  select?: Prisma.OneTimePasswordSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OneTimePassword
   */
  omit?: Prisma.OneTimePasswordOmit<ExtArgs> | null;
  /**
   * Filter, which OneTimePassword to fetch.
   */
  where: Prisma.OneTimePasswordWhereUniqueInput;
};

/**
 * OneTimePassword findUniqueOrThrow
 */
export type OneTimePasswordFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OneTimePassword
   */
  select?: Prisma.OneTimePasswordSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OneTimePassword
   */
  omit?: Prisma.OneTimePasswordOmit<ExtArgs> | null;
  /**
   * Filter, which OneTimePassword to fetch.
   */
  where: Prisma.OneTimePasswordWhereUniqueInput;
};

/**
 * OneTimePassword findFirst
 */
export type OneTimePasswordFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OneTimePassword
   */
  select?: Prisma.OneTimePasswordSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OneTimePassword
   */
  omit?: Prisma.OneTimePasswordOmit<ExtArgs> | null;
  /**
   * Filter, which OneTimePassword to fetch.
   */
  where?: Prisma.OneTimePasswordWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OneTimePasswords to fetch.
   */
  orderBy?:
    | Prisma.OneTimePasswordOrderByWithRelationInput
    | Prisma.OneTimePasswordOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for OneTimePasswords.
   */
  cursor?: Prisma.OneTimePasswordWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OneTimePasswords from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OneTimePasswords.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of OneTimePasswords.
   */
  distinct?:
    | Prisma.OneTimePasswordScalarFieldEnum
    | Prisma.OneTimePasswordScalarFieldEnum[];
};

/**
 * OneTimePassword findFirstOrThrow
 */
export type OneTimePasswordFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OneTimePassword
   */
  select?: Prisma.OneTimePasswordSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OneTimePassword
   */
  omit?: Prisma.OneTimePasswordOmit<ExtArgs> | null;
  /**
   * Filter, which OneTimePassword to fetch.
   */
  where?: Prisma.OneTimePasswordWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OneTimePasswords to fetch.
   */
  orderBy?:
    | Prisma.OneTimePasswordOrderByWithRelationInput
    | Prisma.OneTimePasswordOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for OneTimePasswords.
   */
  cursor?: Prisma.OneTimePasswordWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OneTimePasswords from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OneTimePasswords.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of OneTimePasswords.
   */
  distinct?:
    | Prisma.OneTimePasswordScalarFieldEnum
    | Prisma.OneTimePasswordScalarFieldEnum[];
};

/**
 * OneTimePassword findMany
 */
export type OneTimePasswordFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OneTimePassword
   */
  select?: Prisma.OneTimePasswordSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OneTimePassword
   */
  omit?: Prisma.OneTimePasswordOmit<ExtArgs> | null;
  /**
   * Filter, which OneTimePasswords to fetch.
   */
  where?: Prisma.OneTimePasswordWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OneTimePasswords to fetch.
   */
  orderBy?:
    | Prisma.OneTimePasswordOrderByWithRelationInput
    | Prisma.OneTimePasswordOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing OneTimePasswords.
   */
  cursor?: Prisma.OneTimePasswordWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OneTimePasswords from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OneTimePasswords.
   */
  skip?: number;
  distinct?:
    | Prisma.OneTimePasswordScalarFieldEnum
    | Prisma.OneTimePasswordScalarFieldEnum[];
};

/**
 * OneTimePassword create
 */
export type OneTimePasswordCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OneTimePassword
   */
  select?: Prisma.OneTimePasswordSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OneTimePassword
   */
  omit?: Prisma.OneTimePasswordOmit<ExtArgs> | null;
  /**
   * The data needed to create a OneTimePassword.
   */
  data: Prisma.XOR<
    Prisma.OneTimePasswordCreateInput,
    Prisma.OneTimePasswordUncheckedCreateInput
  >;
};

/**
 * OneTimePassword createMany
 */
export type OneTimePasswordCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many OneTimePasswords.
   */
  data:
    | Prisma.OneTimePasswordCreateManyInput
    | Prisma.OneTimePasswordCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * OneTimePassword createManyAndReturn
 */
export type OneTimePasswordCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OneTimePassword
   */
  select?: Prisma.OneTimePasswordSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the OneTimePassword
   */
  omit?: Prisma.OneTimePasswordOmit<ExtArgs> | null;
  /**
   * The data used to create many OneTimePasswords.
   */
  data:
    | Prisma.OneTimePasswordCreateManyInput
    | Prisma.OneTimePasswordCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * OneTimePassword update
 */
export type OneTimePasswordUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OneTimePassword
   */
  select?: Prisma.OneTimePasswordSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OneTimePassword
   */
  omit?: Prisma.OneTimePasswordOmit<ExtArgs> | null;
  /**
   * The data needed to update a OneTimePassword.
   */
  data: Prisma.XOR<
    Prisma.OneTimePasswordUpdateInput,
    Prisma.OneTimePasswordUncheckedUpdateInput
  >;
  /**
   * Choose, which OneTimePassword to update.
   */
  where: Prisma.OneTimePasswordWhereUniqueInput;
};

/**
 * OneTimePassword updateMany
 */
export type OneTimePasswordUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update OneTimePasswords.
   */
  data: Prisma.XOR<
    Prisma.OneTimePasswordUpdateManyMutationInput,
    Prisma.OneTimePasswordUncheckedUpdateManyInput
  >;
  /**
   * Filter which OneTimePasswords to update
   */
  where?: Prisma.OneTimePasswordWhereInput;
  /**
   * Limit how many OneTimePasswords to update.
   */
  limit?: number;
};

/**
 * OneTimePassword updateManyAndReturn
 */
export type OneTimePasswordUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OneTimePassword
   */
  select?: Prisma.OneTimePasswordSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the OneTimePassword
   */
  omit?: Prisma.OneTimePasswordOmit<ExtArgs> | null;
  /**
   * The data used to update OneTimePasswords.
   */
  data: Prisma.XOR<
    Prisma.OneTimePasswordUpdateManyMutationInput,
    Prisma.OneTimePasswordUncheckedUpdateManyInput
  >;
  /**
   * Filter which OneTimePasswords to update
   */
  where?: Prisma.OneTimePasswordWhereInput;
  /**
   * Limit how many OneTimePasswords to update.
   */
  limit?: number;
};

/**
 * OneTimePassword upsert
 */
export type OneTimePasswordUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OneTimePassword
   */
  select?: Prisma.OneTimePasswordSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OneTimePassword
   */
  omit?: Prisma.OneTimePasswordOmit<ExtArgs> | null;
  /**
   * The filter to search for the OneTimePassword to update in case it exists.
   */
  where: Prisma.OneTimePasswordWhereUniqueInput;
  /**
   * In case the OneTimePassword found by the `where` argument doesn't exist, create a new OneTimePassword with this data.
   */
  create: Prisma.XOR<
    Prisma.OneTimePasswordCreateInput,
    Prisma.OneTimePasswordUncheckedCreateInput
  >;
  /**
   * In case the OneTimePassword was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.OneTimePasswordUpdateInput,
    Prisma.OneTimePasswordUncheckedUpdateInput
  >;
};

/**
 * OneTimePassword delete
 */
export type OneTimePasswordDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OneTimePassword
   */
  select?: Prisma.OneTimePasswordSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OneTimePassword
   */
  omit?: Prisma.OneTimePasswordOmit<ExtArgs> | null;
  /**
   * Filter which OneTimePassword to delete.
   */
  where: Prisma.OneTimePasswordWhereUniqueInput;
};

/**
 * OneTimePassword deleteMany
 */
export type OneTimePasswordDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which OneTimePasswords to delete
   */
  where?: Prisma.OneTimePasswordWhereInput;
  /**
   * Limit how many OneTimePasswords to delete.
   */
  limit?: number;
};

/**
 * OneTimePassword without action
 */
export type OneTimePasswordDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OneTimePassword
   */
  select?: Prisma.OneTimePasswordSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OneTimePassword
   */
  omit?: Prisma.OneTimePasswordOmit<ExtArgs> | null;
};
