name: Publish and Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_push:
    name: Build Apps and Push Image
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build applications
        run: NODE_ENV=production pnpm dlx turbo run build --no-cache -- --mode production
        env:
          NODE_ENV: production

      - name: Prune dependencies
        run: pnpm prune --prod --no-optional

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/me

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy to Docker Swarm
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Copy Files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'docker-compose.yml'
          target: '~/'

      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: INFISICAL_CLIENT_ID,INFISICAL_CLIENT_SECRET,INFISICAL_PROJECT_ID,TAG,DOCKERHUB_USERNAME
          script: |
            export TAG=${{ needs.build_and_push.outputs.tag }}
            export INFISICAL_CLIENT_ID="${{ secrets.INFISICAL_CLIENT_ID }}"
            export INFISICAL_CLIENT_SECRET="${{ secrets.INFISICAL_CLIENT_SECRET }}"
            export INFISICAL_PROJECT_ID="${{ secrets.INFISICAL_PROJECT_ID }}"

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/me:$TAG

            docker stack deploy -c docker-compose.yml --with-registry-auth me

            docker image prune -f
